<?php
/**
 * Created by PhpStorm.
 * User: sp
 * Date: 29/11/15
 * Time: 1:18 AM
 */
$HTMLTags = array ("&lt;!--Comment--&gt;" => "Defines a comment",
"&lt;!DOCTYPE&gt;" => "Defines the document type",
"&lt;a&gt;" => "Defines a hyperlink",
"&lt;abbr&gt;" => "Defines an abbreviation or an acronym",
"&lt;acronym&gt;" => "Not supported in HTML5. Use &lt;abbr&gt; instead.Defines an acronym",
"&lt;address&gt;" => "Defines contact information for the author/owner of a document",
"&lt;applet&gt;" => "Not supported in HTML5. Use &lt;embed&gt; or &lt;object&gt; instead.Defines an embedded applet",
"&lt;area&gt;" => "Defines an area inside an image-map",
"&lt;article&gt;" => "Defines an article",
"&lt;aside&gt;" => "Defines content aside from the page content",
"&lt;audio&gt;" => "Defines sound content",
"&lt;b&gt;" => "Defines bold text",
"&lt;base&gt;" => "Specifies the base URL/target for all relative URLs in a document",
"&lt;basefont&gt;" => "Not supported in HTML5. Use CSS instead.Specifies a default color, size, and font for all text in a document",
"&lt;bdi&gt;" => "Isolates a part of text that might be formatted in a different direction
from other text outside it",
"&lt;bdo&gt;" => "Overrides the current text direction",
"&lt;big&gt;" => "Not supported in HTML5. Use CSS instead.Defines big text",
"&lt;blockquote&gt;" => "Defines a section that is quoted from another source",
"&lt;body&gt;" => "Defines the document's body",
"&lt;br&gt;" => "Defines a single line break",
"&lt;button&gt;" => "Defines a clickable button",
"&lt;canvas&gt;" => "Used to draw graphics, on the fly, via scripting (usually JavaScript)",
"&lt;caption&gt;" => "Defines a table caption",
"&lt;center&gt;" => "Not supported in HTML5. Use CSS instead.Defines centered text",
"&lt;cite&gt;" => "Defines the title of a work",
"&lt;code&gt;" => "Defines a piece of computer code",
"&lt;col&gt;" => "Specifies column properties for each column within a &lt;colgroup&gt; element ",
"&lt;colgroup&gt;" => "Specifies a group of one or more columns in a table for formatting",
"&lt;datalist&gt;" => "Specifies a list of pre-defined options for input controls",
"&lt;dd&gt;" => "Defines a description/value of a term in a description list",
"&lt;del&gt;" => "Defines text that has been deleted from a document",
"&lt;details&gt;" => "Defines additional details that the user can view or hide",
"&lt;dfn&gt;" => "Represents the defining instance of a term",
"&lt;dialog&gt;" => "Defines a dialog box or window",
"&lt;dir&gt;" => "Not supported in HTML5. Use &lt;ul&gt; instead.Defines a directory list",
"&lt;div&gt;" => "Defines a section in a document",
"&lt;dl&gt;" => "Defines a description list",
"&lt;dt&gt;" => "Defines a term/name in a description list",
"&lt;em&gt;" => "Defines emphasized text ",
"&lt;embed&gt;" => "Defines a container for an external (non-HTML) application",
"&lt;fieldset&gt;" => "Groups related elements in a form",
"&lt;figcaption&gt;" => "Defines a caption for a &lt;figure&gt; element",
"&lt;figure&gt;" => "Specifies self-contained content",
"&lt;font&gt;" => "Not supported in HTML5. Use CSS instead.Defines font, color, and size for text",
"&lt;footer&gt;" => "Defines a footer for a document or section",
"&lt;form&gt;" => "Defines an HTML form for user input",
"&lt;frame&gt;" => "Not supported in HTML5.Defines a window (a frame) in a frameset",
"&lt;frameset&gt;" => "Not supported in HTML5.Defines a set of frames",
"&lt;h1&gt; to &lt;h6&gt;" => " Defines HTML headings",
"&lt;head&gt;" => "Defines information about the document",
"&lt;header&gt;" => "Defines a header for a document or section",
"&lt;hr&gt;" => " Defines a thematic change in the content",
"&lt;html&gt;" => "Defines the root of an HTML document",
"&lt;i&gt;" => "Defines a part of text in an alternate voice or mood",
"&lt;iframe&gt;" => "Defines an inline frame",
"&lt;img&gt;" => "Defines an image",
"&lt;input&gt;" => "Defines an input control",
"&lt;ins&gt;" => "Defines a text that has been inserted into a document",
"&lt;kbd&gt;" => "Defines keyboard input",
"&lt;keygen&gt;" => "Defines a key-pair generator field (for forms)",
"&lt;label&gt;" => "Defines a label for an &lt;input&gt; element",
"&lt;legend&gt;" => "Defines a caption for a &lt;fieldset&gt; element",
"&lt;li&gt;" => "Defines a list item",
"&lt;link&gt;" => "Defines the relationship between a document and an external resource (most
used to link to style sheets)",
"&lt;main&gt;" => "Specifies the main content of a document",
"&lt;map&gt;" => "Defines a client-side image-map",
"&lt;mark&gt;" => "Defines marked/highlighted text",
"&lt;menu&gt;" => "Defines a list/menu of commands",
"&lt;menuitem&gt;" => "Defines a command/menu item that the user can invoke from a popup menu",
"&lt;meta&gt;" => "Defines metadata about an HTML document",
"&lt;meter&gt;" => "Defines a scalar measurement within a known range (a gauge)",
"&lt;nav&gt;" => "Defines navigation links",
"&lt;noframes&gt;" => "Not supported in HTML5.Defines an alternate content for users that do not support frames",
"&lt;noscript&gt;" => "Defines an alternate content for users that do not support
client-side scripts",
"&lt;object&gt;" => "Defines an embedded object",
"&lt;ol&gt;" => "Defines an ordered list",
"&lt;optgroup&gt;" => "Defines a group of related options in a drop-down list",
"&lt;option&gt;" => "Defines an option in a drop-down list",
"&lt;output&gt;" => "Defines the result of a calculation",
"&lt;p&gt;" => "Defines a paragraph",
"&lt;param&gt;" => "Defines a parameter for an object",
"&lt;pre&gt;" => "Defines preformatted text",
"&lt;progress&gt;" => "Represents the progress of a task",
"&lt;q&gt;" => "Defines a short quotation",
"&lt;rp&gt;" => "Defines what to show in browsers that do not support ruby annotations",
"&lt;rt&gt;" => "Defines an explanation/pronunciation of characters (for East Asian
typography)",
"&lt;ruby&gt;" => "Defines a ruby annotation (for East Asian typography)",
"&lt;s&gt;" => "Defines text that is no longer correct",
"&lt;samp&gt;" => "Defines sample output from a computer program",
"&lt;script&gt;" => "Defines a client-side script",
"&lt;section&gt;" => "Defines a section in a document",
"&lt;select&gt;" => "Defines a drop-down list",
"&lt;small&gt;" => "Defines smaller text",
"&lt;source&gt;" => "Defines multiple media resources for media elements (&lt;video&gt; and &lt;audio&gt;)",
"&lt;span&gt;" => "Defines a section in a document",
"&lt;strike&gt;" => "Not supported in HTML5. Use &lt;del&gt; or &lt;s&gt; instead.Defines strikethrough text",
"&lt;strong&gt;" => "Defines important text",
"&lt;style&gt;" => "Defines style information for a document",
"&lt;sub&gt;" => "Defines subscripted text",
"&lt;summary&gt;" => "Defines a visible heading for a &lt;details&gt; element",
"&lt;sup&gt;" => "Defines superscripted text",
"&lt;table&gt;" => "Defines a table",
"&lt;tbody&gt;" => "Groups the body content in a table",
"&lt;td&gt;" => "Defines a cell in a table",
"&lt;textarea&gt;" => "Defines a multiline input control (text area)",
"&lt;tfoot&gt;" => "Groups the footer content in a table",
"&lt;th&gt;" => "Defines a header cell in a table",
"&lt;thead&gt;" => "Groups the header content in a table",
"&lt;time&gt;" => "Defines a date/time",
"&lt;title&gt;" => "Defines a title for the document",
"&lt;tr&gt;" => "Defines a row in a table",
"&lt;track&gt;" => "Defines text tracks for media elements (&lt;video&gt; and &lt;audio&gt;)",
"&lt;tt&gt;" => "Not supported in HTML5. Use CSS instead.Defines teletype text",
"&lt;u&gt;" => "Defines text that should be stylistically different from normal text",
"&lt;ul&gt;" => "Defines an unordered list",
"&lt;var&gt;" => "Defines a variable",
"&lt;video&gt;" => "Defines a video or movie",
"&lt;wbr&gt;" => "Defines a possible line-break" );

?>


